name: Rebecca Erickson
favicon: null
layout_spectrum: 0.35738
typography_spectrum: 0.38809
title: Mixed Media Artist
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#060606'
    - '#9b001e'
    - '#de4923'
    - '#a29d7a'
    - '#5d3f18'
  brandStrength: 0.5147451548837125
  lightness: 0.9229587912559509
  saturation: 0.36187838786281645
  rhythmicContrast: 0.843827678821981
purpose: []
