name: RebeccaErickson
favicon: null
layout_spectrum: 0.816136724781245
typography_spectrum: 0.2837707553990185
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.5147451548837125
  lightness: 0.9229587912559509
  saturation: 0.36187838786281645
  rhythmicContrast: 0.843827678821981
purpose: []
